language: php

dist: trusty

matrix:
  include:
    - name: PHP 7.3
      php: 7.3
      dist: precise
    - name: PHP 7.4
      php: 7.4

before_install:
  - travis_retry composer self-update
  - composer install
  
script: phpunit --exclude-group FITS --bootstrap vendor/autoload.php tests